using System.Runtime.CompilerServices;

double n, m, z1, z2,y,x,a,b,c;
Console.WriteLine("Введiть n:");
n = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введiть m:");
m = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введiть x:");
x = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введiть a:");
a = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введiть b:");
b = Convert.ToDouble(Console.ReadLine());
z1 = ((m - 1) * Math.Sqrt(m) - (n - 1) * Math.Sqrt(n)) / (Math.Sqrt(Math.Pow(m, 3) * n) + n * m * Math.Pow(m, 2) - m);
z2 = (Math.Sqrt(m) - Math.Sqrt(n)) / (m);
c = Math.Sin(a - b);
y = 2.4 * Math.Abs((Math.Pow(x, 2) + b) / (a)) + (a - b) * Math.Pow(c, 2) + Math.Pow(10, -2) * (x - b);
Console.WriteLine("Результат z1:" + z1);
Console.WriteLine("Результат z2:" + z2);
Console.WriteLine("Результат y:" + y);