double a, b, c, d ,m ,n,x ;
Console.WriteLine("Enter a = ");
a = double.Parse(Console.ReadLine());
Console.WriteLine("Enter b = ");
b = double.Parse(Console.ReadLine());
Console.WriteLine("Enter c = ");
c = double.Parse(Console.ReadLine());
Console.WriteLine("Enter d = ");
d = double.Parse(Console.ReadLine());
Console.WriteLine("Enter m = ");
m = double.Parse(Console.ReadLine());
Console.WriteLine("Enter n = ");
n = double.Parse(Console.ReadLine());
Console.WriteLine("Enter x = ");
x = double.Parse(Console.ReadLine());
double z1 = ((m-1)*Math.Sqrt(m)-(n-1)*Math.Sqrt(n)) / (Math.Sqrt(m*m*m*n) + n * m + m * m - m);
double z2 = Math.Sqrt(m) - Math.Sqrt(n) / m;
double y = 2.4 * Math.Abs(x * x + b / a) + (a - b) * Math.Pow(Math.Sin(a - b), 2) + Math.Pow(10, -2) * (x - b);
Console.WriteLine($"z1 = {z1}\nz2 = {z2}\ny = {y}");